import Head from 'next/head'
import Image from 'next/image'

import { useRouter } from 'next/router'

import styles from '../styles/Home.module.css'

// Components
import Header from '../components/partials/Header'
import Footer from '../components/partials/Footer'

export default function Home() {

  const router = useRouter()

  const locale = router.locale

  return (
    <div>
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>{locale}</h1>


      <main className={styles.main}>
       
      </main>
      <Footer />
    </div>
  )
}
